### ISSUE TITLE
Quotation mark in the project's directory path breaks `import`

### ISSUE THREAD

**Issue by arnaudgolfouse** [nvarner/typst-lsp#102]
- **Component**: 
    - [ ] VSCode Extension
    - [x] VSCodium Extension
    - [ ] LSP (used with other editor)
- **Extension version**: `0.4.1`
- **LSP version**: `0.4.1`
- **OS version and name**: Ubuntu 22.04

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

When using the extension from a path which contains an quotation mark (`'`), no changes to an imported file seems to be observed. This is best described with an example:

- Create a folder `~/Documents/FolderWith'Quote/project/`, and populate it with files `preamble.typ` and `main.typ`.
- Fill `preamble.typ` with
  ```typst
  #let project(body) = {
    set heading(numbering: "1")
    body
  }
  ```
- Fill `main.typ` with
  ```typst
  #import "preamble.typ": project
  #show : project.with()

  = heading

  After loading the window (for example via `Reload Window`), no subsequent changes to preamble.typ are observed: we can change the numbering of sections, remove all the text in preamble.typ... Nothing will have an effect.
  ```
- Open `~/Documents/FolderWith'Quote/project/` in vscode.
- Change anything in `preamble`, save both files. For me, changes to `preamble` are not reflected in the output `main.pdf` (including e.g. removing everything in `preamble`).

Paths without a quotation mark are handled just fine.

**Comment by nvarner** [comment]
I believe this is fixed in v0.9. Please reopen if it is not.
