### ISSUE TITLE
Prevent compilation of imported files

### ISSUE THREAD

**Issue by beeb** [nvarner/typst-lsp#11]
When a template is extracted into a separate file that gets imported into the main document, the extension will compile an empty PDF when the template file is edited.

This is probably also undesirable for any partial file that gets imported in another document, even if it contains content.

An idea would be to parse files in the workspace to check if they have an `#import` statement, and to avoid generating PDF files for those files that are imported at some point.

Additionally, the extension could trigger a recompile of the main file when an imported file gets modified.

Practically, keeping a map of files that are arguments of an import statement for the workspace would allow both of the above. The map keys would be the imported files and their values would be a set of files where the import statement resides.

**Comment by imbrem** [comment]
Would it also be possible to replicate `typst --watch bleh.typ`'s behavior in that the file is recompiled when an imported file is changed?

**Comment by KronosTheLate** [comment]
Huge plus 1 on this. The extension is great, but this would be a huge benefit. Perhaps some people would want to compile document sections separately, so this should be togglable.

**Comment by beeb** [comment]
Regarding compiling a partial, there is a command to manually compile the active file.
