### ISSUE TITLE
Unable to turn off auto-export-to-pdf

### ISSUE THREAD

**Issue by matthewelmer** [nvarner/typst-lsp#110]
- **Component**:
    - [x] VSCode Extension
- **Extension version**: v0.4.1
- **OS version and name**: Linux Mint 21.1 Cinnamon

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

I cannot seem to turn off auto-export to PDF. When I set `"typst-lsp.exportPdf": "never"`, it will stay off for the session, but if I close VS Code and open it again, auto-compile runs despite my setting it not to. This is a big problem, since auto-compile is currently in an unusable state (see #70 and #11). It's much simpler and more reliable to download the typst binary and use `typst watch <document>.typ`, but the typst watcher seems to not do anything while the extension is already auto-exporting to pdf.

Update: The issue doesn't occur if I start the typst watcher before opening VSCode's pdf viewer. Perhaps the issue is that the typst-LSP extension starts auto-exporting when the user tries to pull up a pdf!

**Comment by beeb** [comment]
I can't seem to reproduce this on either Windows or Ubuntu. If I set my settings to never export, I don't get a PDF when saving or modifying the change. Are you sure you don't have a process of the official typst binary running in the background somehow?

**Comment by matthewelmer** [comment]
Apologies, I was mistaken in my choice of PDF viewer. I was using the one that comes with [LaTeX Workshop](https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop).

I didn't have typst running -- at least not intentionally. I don't see how I could have done something like that, but I wish I would have thought to check. The issue hasn't presented itself since I uninstalled and reinstalled the LaTeX Workshop extension, though. Sorry for the goose chase; I'll reopen this if I notice the problem occur again.
