### ISSUE TITLE
Rendered output does not look the same as compiling manually

### ISSUE THREAD

**Issue by 3nt3** [nvarner/typst-lsp#119]
- **Component**: 
    - [x] VSCode Extension
    - [ ] VSCodium Extension
    - [ ] LSP (used with other editor)
- **Extension version**: v0.4.1
- **OS version and name**: arch linux

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
```typst
$ P(A sect B) = P(B) dot P(A) $
```
does not render the same as with the native compiler (0.3.0 b1e0de00), as in the dots are not centered vertically

![](https://imgur.com/JugxI7C.png)

**Comment by Enter-tainer** [comment]
It's still on v0.2.0. Hope #115 helps

**Comment by Enter-tainer** [comment]
maybe update to https://github.com/typst/typst/commit/27771bc329ab23cc551637fb3feac7b5689e64c7 ? Document become `Send` again now

**Comment by nvarner** [comment]
`Document` being `Send` is exactly what this was blocking on. Thanks for the ping!

**Comment by Enter-tainer** [comment]
> you seem more up-to-date on Typst development;

I just subscribed to https://github.com/typst/typst/issues/930  days ago and got notified when it is closed.😇

> do you know if that commit is stable enough to depend on?

I don't know. The most stable option for us is to wait for the next release(not sure when will the next release comes). Upgrade to that certain commit sounds like a quick hack to me. But it can be useful if a quick upgrade is greatly needed.

**Comment by nvarner** [comment]
Oh, that works too :)

I'm performing the upgrade now, and Typst seems to depend on comemo as a git dependency without specifying a tag, commit, or anything else, and I don't want to release with that. I'll probably push a Typst v0.3.0 branch and not merge it until one of v0.3.1 or v0.4.0 comes out.

**Comment by nvarner** [comment]
That branch is now available as [typst-0.3.0](https://github.com/nvarner/typst-lsp/tree/typst-0.3.0). Very lightly tested, but Seems To Work. I'll leave this issue open until we can upgrade to a stable Typst version.
