### ISSUE TITLE
Autocompletion of citations

### ISSUE THREAD

**Issue by zcorn2017** [nvarner/typst-lsp#157]
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

Hi everyone,

It would be great to have auto completion of citations like "@einstein1921" from .bib files, which would save our time from copying the citations from Zotero.

Thank you in advance,
Zcorn.

**Comment by NickAcPT** [comment]
Regarding this, I came across [a message](https://discord.com/channels/1054443721975922748/1054443722592497796/1156563344258519080) on typst's discord server on how to fix this:

![Discord Message](https://github.com/nvarner/typst-lsp/assets/32451103/963bc0b2-6cbd-455d-9c08-3baeb6fd1cb2)

I experimented a bit locally, but my changes were janky and not clean enough for a PR.

Basically, in [this](https://github.com/nvarner/typst-lsp/blob/74ab2a90c3868badabc579b92e6eaa65aff4e3f1/src/server/typst_compiler.rs#L14) function, after compiling, we have to keep the last compilation around so we can pass frames to the `typst::ide::tooltip` and `typst::ide::autocomplete` functions.

Honestly, I did struggle a bit with understanding what the "frames" were, but it seems to be that it's just the document's pages (`Document#pages`)
