### ISSUE TITLE
Almost everything is highlighted as a keyword

### ISSUE THREAD

**Issue by PgBiel** [nvarner/typst-lsp#166]
- **Component**: 
    - [ ] VSCode Extension
    - [X] VSCodium Extension
    - [ ] LSP (used with other editor)
- **Extension version**: v0.6.2
- **LSP version**: v0.6.2
- **OS version and name**: openSUSE Tumbleweed

- [X] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [X] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

Almost everything seems to be mistakenly highlighted as a keyword since the v0.6.2 update.
![image](https://github.com/nvarner/typst-lsp/assets/9021226/a2dfa432-3bb3-48c4-b177-2c3aa2688a64)

### Logs
(No relevant logs)

**Comment by nvarner** [comment]
I've figured out and fixed the bug (see the [highlight-fixes](https://github.com/nvarner/typst-lsp/tree/highlight-fixes) branch).

Unfortunately, while loading `tablex.typ` for testing, I encountered an unrelated highlighting bug that causes a panic, which you may or may not have also seen. I'm going to investigate that next.

**Comment by nvarner** [comment]
That issue has been fixed, too. Highlighting in the new branch seems to be working as expected in my testing.

**Comment by PgBiel** [comment]
Thanks for the hard work! It's all right now 👍
