### ISSUE TITLE
unclear setup instructions

### ISSUE THREAD

**Issue by bnjmnjrk** [nvarner/typst-lsp#168]
- [x] VSCode Extension
- **Extension version**: 0.6.2
- **LSP version**: 0.6.2
- **OS version and name**: arch linux

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
https://github.com/nvarner/typst-lsp/assets/106487517/ae159a41-4746-4901-b711-8477163a2731

As you can see in the video, the last step in the development cycles (readme.md) does not work. 

I have followed the [development guide](https://github.com/nvarner/typst-lsp#development-guide)
Prerequisites: 
- Rust, Rust Analyzer and Node are installed and activ.

First time setup: 
```sh
pushd addons/vscode
npm install
npm run compile
popd
```

Development cycle:
```sh
cargo install --path .
# open, focus addons/vscode/out/extension.js in vscode  !! i would add this step into the development cycle
# press ctrl + f5
# choose extension development host
# extension doesnt work
```

have i perhaps overlooked something? i would be glad about answers

**Comment by nvarner** [comment]
I'm not sure exactly what the issue is. In the Extension Development Host, can you look at two things?

- Open the Output panel and check the Typst Language Server logs
- See if Typst LSP is listed as an installed extension

**Comment by bnjmnjrk** [comment]
I see my mistake, I opened the parents folder in vscode and not the "typst-lsp" project. That's why the json files in .vscode folder were not recognized. I apologize.
