### ISSUE TITLE
Typst 0.6 is out!

### ISSUE THREAD

**Issue by ice1000** [nvarner/typst-lsp#186]
Please consider updating to the latest version, thanks!

This is a great extension :heart:

**Comment by Enter-tainer** [comment]
FWIW, I've made some attempts to adapt to the latest typst. https://github.com/Enter-tainer/typst-lsp/commit/6f26ded59e0c62c260e9f863474239d7d1b64a55 Hope this helps.

**Comment by nvarner** [comment]
I've been working on an update to Typst v0.6.0, but as a result of those changes, it's a substantial update and is taking a while. If your fork works, it might be a good solution in the meantime.

**Comment by Enter-tainer** [comment]
> it's a substantial update and is taking a while. 

Indeed.

>If your fork works, it might be a good solution

It currently doesn't compile. And it seems that changes related to `Source` and `FileId` requires substantial refractor to current code.

**Comment by nvarner** [comment]
I need to do a bit more testing, but the [typst-0.6.0 branch](https://github.com/nvarner/typst-lsp/tree/typst-0.6.0) is nearly done. I expect to make a release tonight or tomorrow. (Though unfortunately, Typst v0.7.0 just released.... Hopefully it involves fewer breaking changes.)

**Comment by Myriad-Dreamin** [comment]
> I need to do a bit more testing, but the [typst-0.6.0 branch](https://github.com/nvarner/typst-lsp/tree/typst-0.6.0) is nearly done. I expect to make a release tonight or tomorrow. (Though unfortunately, Typst v0.7.0 just released.... Hopefully it involves fewer breaking changes.)

Fortunately, you can step to v0.7.0 quickly :).

**Comment by nvarner** [comment]
The latest release supports Typst 0.6! Typst 0.7 likely coming very soon, since it's been a much smoother transition than 0.6.
