### ISSUE TITLE
LSP won't work when supplied arguments from neovim config

### ISSUE THREAD

**Issue by loutr** [nvarner/typst-lsp#193]
- **Component**: 
    - [ ] VSCode Extension
    - [ ] VSCodium Extension
    - [x] LSP (used with **Neovim**) 
- **LSP version**: 0.7.1
- **OS version and name**: NixOS 23.05/unstable

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
The language server works properly when no option is given, but fails silently as soon as it is given a non-empty setting parameter in the lua config file:
```lua
require("lspconfig").typst_lsp.setup {
    on_attach = on_attach,
    flags = lsp_flags,
    settings = {
        -- commenting this out makes it work
        exportPdf = "never",
    },
}
```
The LSP is still attached to the session, but does not respond at all (no linting etc.)

### Logs

This LSP is not very talkative in Neovim, and the logs are identical whether it is dead or not.
```
[START][2023-07-05 12:49:31] LSP logging initiated
[WARN][2023-07-05 12:49:31] ...lsp/handlers.lua:137	"The language server typst_lsp triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

**Comment by zcorn2017** [comment]
> I have the same problem, with the config from the README
> 
> ```lua
> require'lspconfig'.typst_lsp.setup{
>     settings = {
>         exportPdf = "onType" -- Choose onType, onSave or never.
>     }
> }
> ```
> 
> the LSP gets attached but does nothing, but with an empty config like this
> 
> ```lua
> require'lspconfig'.typst_lsp.setup{}
> ```
> 
> the LSP works as expected.

I wrote this part of README, and this configuration works in the previous versions of typst (before 0.6) and typst-lsp (before 0.7). (BTW I have the same issue and I have no time to fix it now. ) Could you plz update the README file if you have found the workaround for the latest release?

**Comment by tbethe** [comment]
@loutr have you set the lsp log level do debug when looking at the logs? 

`vim.lsp.set_log_level("debug")`

If not, it might make the lsp a bit more 'talkative'.

I also have to report that it works fine for me using the config in the README. I am using `mason-lspconfig` but since that's basically wrapping `lspconfig` I do not think that should matter.

**Comment by MangoIV** [comment]
for me the highlighting seems to work but not the autocompletion - does anybody know the latest working versions so I can check whether at least those work?

**Comment by loutr** [comment]
Sorry for the late reply. Here are the logs I get with a `debug` level: [lsp.log](https://github.com/nvarner/typst-lsp/files/12281429/lsp.log). I don't use Mason or anything, I configure it directly with Nix, but I don't think it matters either.
