### ISSUE TITLE
Remove code completion in text mode

### ISSUE THREAD

**Issue by mcendu** [nvarner/typst-lsp#201]
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

Currently, typst-lsp features code completion when editing normal text, providing useful snippets like numbered lists etc. I find it more annoying than being useful; it gets in the way of writing more often than it can provide help.

I hereby propose the removal of this feature; if not desired, at least make disabling it an option.

**Comment by psads-git** [comment]
I am in full agreement with this feature request.

Is there some workaround that save us out of this permanent annoying behavior of `typst-lsp`?

**Comment by Enter-tainer** [comment]
#387

**Comment by Myriad-Dreamin** [comment]
completed by #387
