### ISSUE TITLE
Does it support format code by typst-fmt(typstfmt)?

### ISSUE THREAD

**Issue by Freed-Wu** [nvarner/typst-lsp#204]
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

<https://github.com/astrale-sharp/typstfmt>

**Comment by Myriad-Dreamin** [comment]
Recording an approach for vscode here. https://github.com/typst/typst/pull/1811#issuecomment-1666478850
