### ISSUE TITLE
version flag on the typst-lsp command

### ISSUE THREAD

**Issue by slashformotion** [nvarner/typst-lsp#211]
- [X] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request
It would be great to have a version command or flag that would print the version of the lsp, see an example below

```sh
$ typst-lsp version
typst-lsp version 0.7.1
$
```

**Comment by nvarner** [comment]
This has been added in the latest version as `typst-lsp --version`.

**Comment by pacak** [comment]
```rust
// TODO: is there a good way to get this automatically at build time?
pub const TYPST_VERSION: &str = "0.7.0";
```

You could add a dev-dependency on `cargo-metadata` and have a test that reads the actual version with cargo-metadata and compares it with this constant and fails if it doesn't match. Alternatively this test might write version to a file which you can `include!` as a string. Test should fail if version is not up to date.
