### ISSUE TITLE
Typst packages don't work

### ISSUE THREAD

**Issue by ChHecker** [nvarner/typst-lsp#212]
- **Component**:
    - [x] VSCode Extension
    - [ ] VSCodium Extension
    - [ ] LSP (used with other editor)
- **Extension version**: 0.7.2
- **LSP version**: 0.7.2
- **OS version and name**: macOS 13.5

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
Importing packages introduced in [https://github.com/typst/packages](https://github.com/typst/packages) doesn't work. Both the local path isn't taken into account (e.g. `#import "@local/diverential:0.1.0": *`), nor are packages downloaded from the preview (e.g. `#import "@preview/big-todo:0.2.0": *`). Both of these work in the Typst executable.
The error is `file not found (searched at {workspace-dir}/@preview/big-todo:0.2.0)` (my user removed for privacy reasons).

### Logs
Logs don't include anything relevant.

**Comment by fschwalbe** [comment]
See #186

**Comment by nvarner** [comment]
The latest release has added support for packages.
