### ISSUE TITLE
typst-lsp blocks on recompilation of the document when used with `nvim` 

### ISSUE THREAD

**Issue by MangoIV** [nvarner/typst-lsp#213]
- **Component**: 
    - ~~VSCode Extension~~
    - ~~VSCodium Extension~~
    - [x] LSP (used with other editor)
- **Extension version**: n/a 
- **LSP version**: 0.7.2 
- **OS version and name**: NixOS 23.11 Tapir 

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

The typst language server blocks on recompilation of the document which is sometimtes annoying in larger documents because the editor becomes unresponsive for the time it does.

Maybe it's easy to do this asynchronously 

### Logs

n/a

**Comment by nvarner** [comment]
Meant to reply a bit ago: this should have been fixed in the recent 0.8.0 update. Please reply if it's not fixed for you.
