### ISSUE TITLE
typst-lsp.serverPath only works when providing full binary location

### ISSUE THREAD

**Issue by NobbZ** [nvarner/typst-lsp#214]
- **Component**: 
    - [X] VSCode Extension
    - [ ] VSCodium Extension
    - [ ] LSP (used with other editor)
- **Extension version**: 0.7.2 
- **LSP version**: 0.7.2 
- **OS version and name**: NixOS 23.11.20230728.2a9d660 (Tapir) 

- [X] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [X] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

The setting `typst-lsp.serverPath` seems to be without any effect.

On NixOS we can not use prebuild dynamically linked programs vor various reasons that I won't dig into now, please just take this for granted.

Therefore I wanted to use the `nixpkgs` provided `typst-lsp` package. With setting `"typst-lsp.serverPath" = "typst-lsp"`, hoping then the plugin would resolve via `PATH` as many others do, I still got a failure that starting the LSP from the plugin location failed.

The only way to make it work is to provide the full absolute location of the typst-lsp, which on a typical NixOS setup might change on a daily basis.

It would be nice if there was a way to configure `PATH` lookup.

### Logs

The following error appears whenever I use an inexisting `typst-lsp.serverPath`, regardless of its exact value. (the logs are missing a check for the specified value, thats probably an extra issue)

```
[Error - 9:14:02 AM] Typst Language Server client: couldn't create connection to server.
Launching server using command /home/nmelzer/.vscode/extensions/nvarner.typst-lsp-0.7.2-linux-x64/out/typst-lsp failed. Error: spawn /home/nmelzer/.vscode/extensions/nvarner.typst-lsp-0.7.2-linux-x64/out/typst-lsp ENOENT
```

**Comment by NobbZ** [comment]
In a project specific shell. I never install LSP in the system.

**Comment by fschwalbe** [comment]
Oh sorry, totally forgot about that.
