### ISSUE TITLE
Add typst-LSP to Lapce plugins

### ISSUE THREAD

**Issue by ma7thmaster** [nvarner/typst-lsp#221]
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

Add typst-LSP to Lapce plugins. Lapce is a lightweight native text editor with LSP support. Thanks!
https://github.com/lapce/lapce

**Comment by ma7thmaster** [comment]
When compiling the LSP to the target wasi, which is required for Lapce plugins, I get the error 471 | compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");

**Comment by nvarner** [comment]
I looked into this recently, and I don't think the LSP needs to be compiled to WASM. Lapce extensions need to be, but it looks like an LSP extension mostly tells Lapce where to find a native LSP binary.
