### ISSUE TITLE
Displaying `today()` differently with released typst build

### ISSUE THREAD

**Issue by LingkKang** [nvarner/typst-lsp#225]
- **Component**:
    - [x] VSCode Extension

- **Extension version**:

`v0.7.2` The latest

- **LSP version**:

`v0.7.2` The latest

- **OS version and name**:

Windows 10 Pro 22H2

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

Typst code: 

``` Typst
Today is #datetime.today().display().
```

The exported PDF is expected to be "**Today is 2023-08-08.**" as stated on the Typst [docs on `datetime.today`](https://typst.app/docs/reference/construct/datetime/#datetime-today). This is also what I get when compiling it with Typst `0.7.0 (da8367e1)` (the latest).

However, when saving the `typ` file, Typst LSP will automatically export a PDF (set `"typst-lsp.exportPdf": "onSave"`), with content "**Today is 2023-08-08 22:51:16.**"

The LSP displays the date with current time which is different from the compiled result.

I tried to simplify the file and left this single line, and it is 100% reproducible, so it is presumably a bug.

### Logs

The output logs are as follows. Will they be helpful?

```
[Info  - 10:57:03 PM] src\server\lsp.rs:468 { message = new settings applied; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\src\lib.rs:77 { message = Starting evaluation; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\src\model\mod.rs:44 { message = Starting typesetting; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\src\model\mod.rs:59 { message = Layout iteration 0; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\library\src\layout\mod.rs:134 { message = Starting layout; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\library\src\meta\document.rs:48 { message = Document layout; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\library\src\layout\page.rs:287 { message = Page layout; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\library\src\layout\mod.rs:207 { message = Layouting `Content`; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\library\src\layout\page.rs:350 { message = Layouting page #1; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\library\src\layout\page.rs:370 { message = Layouting header; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\library\src\layout\page.rs:370 { message = Layouting footer; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\library\src\layout\page.rs:370 { message = Layouting background; }
[Info  - 10:57:06 PM] C:\Users\runneradmin\.cargo\git\checkouts\typst-6808799b0d8fdaa9\3a8b9cc\library\src\layout\page.rs:370 { message = Layouting foreground; }
[Info  - 10:57:06 PM] src\server\export.rs:19 { message = exported PDF; output_path = "e:\\typst\\test.pdf"; }
```

**Comment by nvarner** [comment]
I suspect this is because the LSP is several versions behind. It currently targets Typst 0.5, but a new release for Typst 0.6 is nearly done and will hopefully be out tonight. That means Typst 0.7 support is a ways out.

**Comment by OverHash** [comment]
> 

It's the other way around. `datetime.today()` in the Typst CLI returns a `datetime` object but _without the time specified_ (so it's a `Datetime::Date`). Typst LSP implements `datetime.today()` with the time specified as well - which results in this discrepancy.

**Comment by nvarner** [comment]
Thanks for referencing those docs. Based on that, it looks like `datetime.today` is not intended to return hour, minute, second data, so this really is a bug and not a version issue that might have resolved on its own.

This is probably a quick fix, so I hope to get it into the next release after v0.9.1.

**Comment by nvarner** [comment]
Should be fixed in the next release.
