### ISSUE TITLE
Files with Chinese names are saved using encoding, and the original characters should be preserved.

### ISSUE THREAD

**Issue by relic-yuexi** [nvarner/typst-lsp#236]
- **Component**: 
    - VSCode Extension
    
- **Extension version**: latest
- **LSP version**: latest
- **OS version and name**: windows 11

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

![Snipaste_2023-08-13_12-16-21](https://github.com/nvarner/typst-lsp/assets/53668275/af054fde-3eac-4abe-ae8a-a4a5633f8de1)

As the picture shows, the file name transform URL code, it will lead some errors, like preview can't find file.

 

### Logs

```
Include any logs if relevant, otherwise remove this code block.
```

**Comment by nvarner** [comment]
I just pushed a fix for this. It should be working in the next release.
