### ISSUE TITLE
LSP export regression between 0.9.1 and 0.9.2

### ISSUE THREAD

**Issue by OverHash** [nvarner/typst-lsp#250]
Using the LSP 0.9.2 version over LSP 0.9.1 has resulted in a regression where the Typst LSP will not compile files on Ubuntu 22.04.

The LSP will attempt to compile, but fails and logs
```
[Error - 11:54:10] src/server/lsp.rs:246 { message = could not handle source save; err = expected Typst source file, but found something else; uri = file:///home/.../summary.typ; }
```
(omitted the OS path with `...`)

A minimal repro is creating a `.typ` file and trying to export it.

**Comment by nvarner** [comment]
I've found the issue. Should get a fix out soon.

**Comment by nvarner** [comment]
This should be fixed in the latest release. Please reopen if the issue persists. Thank you for the report!
