### ISSUE TITLE
Use of the typst logo

### ISSUE THREAD

**Issue by Enivex** [nvarner/typst-lsp#272]
I noticed that https://marketplace.visualstudio.com/items?itemName=nvarner.typst-lsp uses the typst logo

According to https://typst.app/legal/brand/, this is not acceptable

> NOT OKAY: Using the unmodified logo or the Typst 't' as the logo for your project.

**Comment by laurmaedje** [comment]
Permission was given here: https://github.com/nvarner/typst-lsp/discussions/15#discussioncomment-5425418
