### ISSUE TITLE
Support for older vscode versions

### ISSUE THREAD

**Issue by giacomogallina** [nvarner/typst-lsp#30]
Hi, I wanted to try the vscode extension, but it seems to only support vscode >= 1.75, while in my distro's repos there's vscode 1.73. Is this version requirement completely recessary, or could it be relaxed a little bit?

**Comment by nvarner** [comment]
It will be relaxed to 1.71 in the next release.

**Comment by giacomogallina** [comment]
thanks a lot!

**Comment by giacomogallina** [comment]
The latest release fixed this issue, so i'm closing it. Thanks again for the fast fix!
