### ISSUE TITLE
Weird delay for onSave event

### ISSUE THREAD

**Issue by beeb** [nvarner/typst-lsp#31]
Looking at the output pane, it takes 7-10 seconds after I save the document to trigger the file write. The execution itself is fast, it's the notification that doesn't get sent by the client immediately.

Not sure if that's the intended behavior (debouncing) as I'm not familiar with the vscode extension library. Ideally we could speed this up.

**Comment by beeb** [comment]
Doesn't happen anymore, maybe it was because it was compiled in debug mode.. Will do more testing

**Comment by nvarner** [comment]
I've also noticed delays in debug mode. Rust is notoriously slow in debug mode, so it wouldn't shock me if that's the whole problem. I'll close for now, but might reopen/open a new issue if the cause is different, or debug builds are too slow to be practical for testing.

**Comment by beeb** [comment]
No worries, from the logging I think it's actually the VSCode extension debug mode that is slow, because the notification doesn't get sent to the LSP during that time. Once the notification is received, the processing on the rust side is fast.
