### ISSUE TITLE
Set default tab size

### ISSUE THREAD

**Issue by Marmare314** [nvarner/typst-lsp#318]
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

It would be nice if the default tab size would be set to `2` for `.typ` files, which is also the default in the web editor.

**Comment by nvarner** [comment]
I think this is a reasonable default to set. I'll look into implementing this.
