### ISSUE TITLE
Clippy lints are not enforced in CI

### ISSUE THREAD

**Issue by beeb** [nvarner/typst-lsp#32]
Right now clippy lints are not causing an error in CI, they just raise warnings (e.g. https://github.com/nvarner/typst-lsp/actions/runs/4523508185/jobs/7966681325)

Is that something that we want to change to enforce consistency?

The following command causes errors on clippy warnings: `cargo clippy -- -Dwarnings`

**Comment by CGMossa** [comment]
Can it be a check that every PR gets, but not a necessity for merging? It is a giant headache when clippy suddenly changes with approved / stabilised lints.
I think it is a good source for "Good-First-Issues" for people to solve clippy-compliance issues.

**Comment by beeb** [comment]
@CGMossa good point. I think one of the open PRs suggests a github action that posts a comment in the PR with the clippy warnings. That would be a good middle ground.

**Comment by nvarner** [comment]
Yep, #20 is likely to affect this. I expect to resolve this issue either in that PR or after it's merged, since the CI workflows will likely change a lot.

**Comment by beeb** [comment]
Actually scratch that, the `actions-rs/clippy-check` action is unmaintained and doesn't work for PRs originating from forks (which is most of them).

**Comment by nvarner** [comment]
This will soon be resolved by #63, which puts clippy into its own job and errors out on warnings.
