### ISSUE TITLE
Reference and Citation Completion

### ISSUE THREAD

**Issue by daskol** [nvarner/typst-lsp#323]
It seems that there is no support for completion of reference labels. There is completion in case of neither `@entry1` expression nor `#cite("entry1", "entry2")` function call. It would be great to complete at least a single entry within `@`-syntax but support for completion in context `cite()` function is desired as well.

**Comment by NickAcPT** [comment]
I think this is a duplicate of #157, at least for the `@`-syntax

**Comment by Enivex** [comment]
This can be closed @nvarner
