### ISSUE TITLE
highlight Labels and References

### ISSUE THREAD

**Issue by nineff** [nvarner/typst-lsp#327]
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

Labels like `<label>` should be highlighted in a different color as the rest of the text/code, same with @-References like `@label`.
The Typst Webapp already does this, and I think the LSP should do this as well.

**Comment by nvarner** [comment]
This is already technically implemented, but it looks like I didn't implement it in a way supported by many themes. A fix will be merged soon. If it does not fix this issue for your theme, please open a new issue.
