### ISSUE TITLE
Define a main file and only compile the main file.

### ISSUE THREAD

**Issue by SebastianJL** [nvarner/typst-lsp#328]
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

It would be really nice if it would be possible to define a main file per project.
- The lsp would only compile the main file.
- The lsp would recompile the main file on changes of #included or #imported files.

At the moment if I write for example a `template.typ` file it will be compiled on save. This just results in an empty pdf which is useless. In turn I will have to change back to my `main.typ` and save it manually to see the changes in my `template.typ` take effect.

I would also suggest that if there is a `main.typ` in the root folder that it will be recognized as the main file by default. Or is there a more common filename for the main file? Maybe there is also some other mechanism from which the main file could be deteremined.

**Comment by SebastianJL** [comment]
I'm very new to typst, so please excuse if something about the request is stupid.

**Comment by DaAlbrecht** [comment]
Hey i think that there is no solution for this at the moment. Its related to this issue i think: https://github.com/nvarner/typst-lsp/issues/285

my workflow at the moment is just to use the typst cli `watch` command on your "main" file:

```bash
typst watch <filename>  
```
Additionally there seems to be an issue in disabling the lsp to generate a pdf: https://github.com/nvarner/typst-lsp/issues/265

To work around this i just add `*.pdf` to my `.gitignore`

Hope that helps

**Comment by SebastianJL** [comment]
Thanks for the answer and the link to the other issue. 
You're tip helps for not generating empty files but it won't recompile the main file on changing the template file.

**Comment by DaAlbrecht** [comment]
hm as long as the template is included in "main" it should work.
Could you maybe provide an example setup?

**Comment by SebastianJL** [comment]
> hm as long as the template is included in "main" it should work. Could you maybe provide an example setup?

Ah sorry, my bad. I didn't try it out, I just read the help 

>$typst watch --help
Watches an input file and recompiles on changes

and inffered from that that it wouldn't recompile on changes of imported files.

Well thanks a lot for the help. I'll close since there is already another issue.
