### ISSUE TITLE
Font lookup not working when compiling on save

### ISSUE THREAD

**Issue by fschwalbe** [nvarner/typst-lsp#358]
- **Component**: 
    - LSP (used with other editor)
- **LSP version**: 0.11.0
- **OS version and name**: NixOS 23.11

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

Typst recently gained support for finding fonts via fontconfig in https://github.com/typst/typst/pull/2472.
But typst-lsp does not seem to do this when compiling a document on save.

## How to reproduce
If you are on a Linux system with fonts installed in a non-standard location (like NixOS), simply compile any document that uses such a font. The typst CLI will correctly find and use the font, while typst-lsp does not and instead falls back to the default font.

**Comment by PgBiel** [comment]
A more suitable title for this issue would likely be "Missing fontconfig support"

**Comment by PgBiel** [comment]
For @fschwalbe and other NixOS users: while my PR isn't merged, you may compile the LSP from source using my PR's branch to remedy this. I basically adapted the solution used in the Typst CLI to the Typst LSP. :+1:
