### ISSUE TITLE
Extension setting page for typst has no setting

### ISSUE THREAD

**Issue by mojtaba82** [nvarner/typst-lsp#36]
I use code oss 1.76 version in linux.  Extension setting page for typst has no setting.
![image](https://user-images.githubusercontent.com/4151722/227772350-2352ef43-5b8f-41cb-9a4c-39d4695a77fe.png)

**Comment by beeb** [comment]
Already merged

**Comment by mojtaba82** [comment]
Now setting page is OK but not compile pdf. nor on save neither on typing.

**Comment by beeb** [comment]
> Now setting page is OK but not compile pdf. nor on save neither on typing. 

Check the output pane in vscode, select the lsp extension in the drop down and report what the logs say. It can take a few seconds for the onSave event to trigger.

**Comment by mojtaba82** [comment]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:36:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by beeb** [comment]
This is the line for reference:

https://github.com/nvarner/typst-lsp/blob/b0ce1087169cf0f8fe9cfe287b38cbe8a92d56d2/src/main.rs#L36
