### ISSUE TITLE
Autocompletion for package import

### ISSUE THREAD

**Issue by Enivex** [nvarner/typst-lsp#367]
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

See title 🙂

**Comment by lace-wing** [comment]
Really want to know if this is going to be implemented in near future. Or I have to switch editor and the workflow for typst...

**Comment by Enivex** [comment]
> Really want to know if this is going to be implemented in near future. Or I have to switch editor and the workflow for typst...

Keep in mind that typst-lsp is not official, and relies on volunteer work. If you're impatient, go with the typst web app.

**Comment by KagaJiankui** [comment]
[OrangeX4/vscode-typst-sync](https://github.com/OrangeX4/vscode-typst-sync) provides basic online & offline package indexing utility. The implementation of the package import autocompletion might reference from this project.

**Comment by ntjess** [comment]
@nvarner I see this is marked as done, but only `@preview` is currently autocompleted. Will you consider adding the `@local` namespace as well, given this is an official [typst-recommended](https://github.com/typst/packages?tab=readme-ov-file#local-packages) prefix?
