### ISSUE TITLE
Enable word-wrap in editor

### ISSUE THREAD

**Issue by BlueskyFR** [nvarner/typst-lsp#37]
When doing split-screen with the PDF on the right, the code on the left window is not wrapped and overflows.
This is set on a per-language basis IIRC.

**Comment by BlueskyFR** [comment]
When language = **Typst**:
![image](https://user-images.githubusercontent.com/25421460/227814710-7c8c4e92-bf24-45cb-9216-fff93168fc31.png)

And when language is **Markdown**:
![image](https://user-images.githubusercontent.com/25421460/227814752-fe3d1dac-cfeb-46c5-888f-f9535870eadb.png)

**Comment by nvarner** [comment]
About to be fixed by #53 and will be in the next extension release.
