### ISSUE TITLE
Irrelevant autocompletion for any text

### ISSUE THREAD

**Issue by TheJiahao** [nvarner/typst-lsp#380]
- **Component**: 
    - VSCode Extension
- **Extension version**: 0.12.0
- **OS version and name**: Windows 11 23H2

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

Since version 0.12.0, almost any text triggers irrelevant completion.
![image](https://github.com/nvarner/typst-lsp/assets/42709836/9053f997-72fb-4ac6-9475-b97f5ee1d496)
![image](https://github.com/nvarner/typst-lsp/assets/42709836/89f97499-bb40-416d-97f2-ac182e745312)

**Comment by KeqiZeng** [comment]
Same issue here🙋‍♂️

**Comment by 1bitbool** [comment]
Same issue. It makes me have to cancel auto-completion every time I want to line break.

**Comment by MaybeBin** [comment]
I had the same problem
