### ISSUE TITLE
Add `@preview` packages autocompletion

### ISSUE THREAD

**Issue by Andrew15-5** [nvarner/typst-lsp#383]
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request
I've noticed that the web app can show suggestions when writing an import statement and adding `@`:
![image](https://github.com/nvarner/typst-lsp/assets/37143421/9922aaa8-ad54-42b0-bc97-bf03061591c6)

It will be very productive if the LSP server can print which packages are available and autocomplete them for you. The note from the https://typst.app/docs/packages/ for each package will be nice to see. This will make the process of finding "that one package" or looking through the list of "what can I use for my project?" much easier.

The only restriction that I see is packages going out of date after the new LSP version being released. I don't know how hard the implementation or good the idea of real time fetching for the latest list of all available packages/version is, but adding an option into settings `fetch-latest-packages` will resolve the "outdated packages" problem.

**Comment by OrangeX4** [comment]
VS Code Typst Sync extension already has this feature, but it's always the latest package fetched from [https://packages.typst.org/preview/index.json](https://packages.typst.org/preview/index.json) in real time.
