### ISSUE TITLE
Autocomplete is annoying

### ISSUE THREAD

**Issue by planetoryd** [nvarner/typst-lsp#405]
When I type in entirely irrelevant raw text it shows the autocomplete menu, which lags terribly (feels like 200ms) every keystroke

![image](https://github.com/nvarner/typst-lsp/assets/68096727/58229808-726a-486a-93b8-56d02a388138)

Also the items in this menu are almost useless. They are just some basic typst syntax. I only need `sym.somesymbol` etc.

**Comment by planetoryd** [comment]
![image](https://github.com/nvarner/typst-lsp/assets/68096727/2527cac7-b599-46e5-965a-ed42762060df)

I set LSP to the manually compiled from master.

That `explict` is set to false should prevent that problem

**Comment by Enter-tainer** [comment]
Latest version should solve this issue

**Comment by planetoryd** [comment]
Yes, I said that

**Comment by Enter-tainer** [comment]
so this issue can be closed now?

**Comment by planetoryd** [comment]
Yes
