### ISSUE TITLE
[Feature Request]: Configuration to compile selected typst files instead of every file

### ISSUE THREAD

**Issue by yoonghm** [nvarner/typst-lsp#406]
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request
There is a configuration option: *Export Pdf* with the following alternatives:
- `never`
- `onSave`
- `onType`

I would suggest a features:
If `onSave` is selected, a suboption is enabled to allow user to select an *overall* or *top-level* or *main* typst file to be compiled. With this feature, this extension will not create too many PDF files.

Thank you for the program and hard work!

**Comment by Enter-tainer** [comment]
https://github.com/nvarner/typst-lsp/pull/389 should help this. It introduce the idea of "pinning" a main file. It is like the eye icon in webapp. Can you try it?

**Comment by KagaJiankui** [comment]
Typst supports `typst watch file.typ out.pdf`, and the CLI output can be configured via CLI options(you may use `typst watch --help`). You may use VSCode build tasks or Makefile to configure "build current editing file" and "typst watch current file" manually, with compiler error parsing support.

Example `tasks.json`:

``` json
  "tasks": {
    "version": "2.0.0",
    "tasks": [
      {
        "label": "Typst - Compile",
        "type": "shell",
        "command": "typst",
        "args": [
          "compile",
          "--diagnostic-format=short",
          "${fileBasename}",
          "${fileBasenameNoExtension}.pdf"
        ],
        "group": "build",
        "presentation": {
          "reveal": "always"
        },
        "options": {
          "cwd": "${fileDirname}"
        },
        "problemMatcher": {
          "owner": "typst",
          "fileLocation": "absolute",
          "pattern": [
            {
              "regexp": "^(?:\\\\\\\\\\?\\\\)(\\w:.*\\.typ):(\\d+):(\\d+):\\s+(\\w+):\\s+(.*)$",
              "file": 1,
              "line": 2,
              "endColumn": 3,
              "severity": 4,
              "message": 5
            }
          ]
        }
      },
      {
        "label": "Typst - Watch",
        "type": "shell",
        "command": "typst",
        "isBackground": true,
        "args": [
          "watch",
          "--diagnostic-format=short",
          "${fileBasename}",
          "${fileBasenameNoExtension}.pdf"
        ],
        "group": {
          "kind": "test",
          "isDefault": true
        },
        "presentation": {
          "reveal": "silent"
        },
        "options": {
          "cwd": "${fileDirname}"
        },
        "problemMatcher": {
          "owner": "typst",
          "fileLocation": "absolute",
          "pattern": [
            {
              "regexp": "^(?:\\\\\\\\\\?\\\\)(\\w:.*\\.typ):(\\d+):(\\d+):\\s+(\\w+):\\s+(.*)$",
              "file": 1,
              "line": 2,
              "endColumn": 3,
              "severity": 4,
              "message": 5
            }
          ],
          "background": {
            "activeOnStart": true,
            "beginsPattern": "^writing\\sto.*\\.pdf$",
            "endsPattern": "^\\[\\d+:\\d+:\\d+\\].*$"
          }
        }
      }
    ]
  }
```

**Comment by yoonghm** [comment]
That is great! Is there a document on how to enable it?

**Comment by Enter-tainer** [comment]
you may checkout the configs. there are more variants other than 
never
onSave
onType.

![Screenshot_2024-01-05-00-39-59-533_com.github.android.jpg](https://github.com/nvarner/typst-lsp/assets/25521218/655b2c94-b5ec-45b8-8c51-041c8ee8773f)
