### ISSUE TITLE
thread 'main' panicked at src/lsp_typst_boundary.rs:101:58

### ISSUE THREAD

**Issue by Parsifa1** [nvarner/typst-lsp#427]
- **Component**: 
    - LSP (used with Neovim)
- **LSP version**: v0.12.1
- **OS version and name**: Arch Linux 5.15.123.1-microsoft-standard-WSL2

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
LSP panics after a random period of time (it's true ,I don't observe any pattern, but it always ends up panic)

### Logs

```
[START][2024-01-31 01:44:55] LSP logging initiated
[WARN][2024-01-31 01:44:55] ...lsp/handlers.lua:134	"The language server typst_lsp triggers a registerCapability handler for workspace/didChangeConfiguration despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2024-01-31 01:46:25] .../vim/lsp/rpc.lua:31	"rpc"	"/home/parsifa1/.local/share/nvim/mason/bin/typst-lsp"	"stderr"	"thread 'main' panicked at src/lsp_typst_boundary.rs:101:58:\ncalled `Option::unwrap()` on a `None` value\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
```

**Comment by Enter-tainer** [comment]
#145 duplicate issue
