### ISSUE TITLE
[Feature Request] Symbol picker

### ISSUE THREAD

**Issue by Ciflire** [nvarner/typst-lsp#428]
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

Would it be possible to implement a symbol picker for heading/functions?
[Related discussion here](https://canary.discord.com/channels/1054443721975922748/1102176239764131901/1203829590703734854)

**Comment by astrale-sharp** [comment]
Where was this completed?

**Comment by Ciflire** [comment]
i have to admit, i don't know, but i'm able to do pick titles and function definition, maybe that was already there and i didn't see it
![image](https://github.com/nvarner/typst-lsp/assets/39668077/6c4f211c-49ac-4847-adba-ab2541de2724)

**Comment by astrale-sharp** [comment]
alrighty :laughing:
