### ISSUE TITLE
Remove linebreaks within a paragraph when performing auto formatting

### ISSUE THREAD

**Issue by yjcui** [nvarner/typst-lsp#465]
First thanks for this great extension!

I am using this extension with VSCode. When performing file formatting, automatic linebreaks will be inserted to break a paragraph, leaving a weired display of multiple lines with different length. Is it possible to keep one paragraph as a single line (in the sense that only one line number  for one paragraph in VSCode) and leave the 'linebreak' to the word wrap function from VSCode? 

Thanks!

**Comment by astrale-sharp** [comment]
Hey there :) 
Could you open this issue in [typstfmt](https://github.com/astrale-sharp/typstfmt) instead and provide an example snippet of your problem? thank you :)

@yjcui
