### ISSUE TITLE
Multiline comments aren't highlighted

### ISSUE THREAD

**Issue by yonatankremer** [nvarner/typst-lsp#468]
- **Component**: 
    - VSCode Extension
- **Extension version**: <v0.13.0>
- **LSP version**: <v0.13.0>
- **OS version and name**: <macOS 14.4.1 >

- I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

### Logs

```
Include any logs if relevant, otherwise remove this code block.
```

**Comment by Myriad-Dreamin** [comment]
duplicated, #264
