### ISSUE TITLE
Hope to support to hide preview button.

### ISSUE THREAD

**Issue by cbk6028** [nvarner/typst-lsp#492]
- I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

![image](https://github.com/nvarner/typst-lsp/assets/147920138/3e86b6c9-b227-4f2a-b74c-85b1c91216d5)
![image](https://github.com/nvarner/typst-lsp/assets/147920138/a553517f-ed6b-4b7f-a42c-28cb761317bd)

typst-preview extension: https://github.com/Enter-tainer/typst-preview supports to preview typst without generating pdf and render in real time. I think it is better to use. But I often click typst-lsp preview button mistakenly , which lies the left of typst-preview button.

**Comment by Myriad-Dreamin** [comment]
Is there a better position to show an export button?

**Comment by cbk6028** [comment]
> Is there a better position to show an export button?

I have no better suggestions about it.
I think that it only need add a check button in settings to disable the preview feature.

**Comment by Enter-tainer** [comment]
At this moment you may right click the icon and hide one of them manually. See also https://github.com/Enter-tainer/typst-preview/issues/255

**Comment by cbk6028** [comment]
> At this moment you may right click the icon and hide one of them manually. See also [Enter-tainer/typst-preview#255](https://github.com/Enter-tainer/typst-preview/issues/255)

Ok. It's exactly what l wanted.
