### ISSUE TITLE
Error handling highlights wrong line in compiled file when error is in a module

### ISSUE THREAD

**Issue by betoma** [nvarner/typst-lsp#57]
- **Component**: 
    - [x] VSCode Extension
    - [ ] VSCodium Extension
    - [ ] LSP (used with other editor)
- **Extension version**: v0.3.0
- **OS version and name**: Ubuntu 20.04

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
Made a .typ file containing several functions. The active .typ file imported the functions from this file as a module. When I saved the active file and an error was thrown due to a problem in one of the imported functions, the listed line and column number were for the error's position in the imported file. However, _that_ line number was underlined as an error in the actively compiled file, rather than the line that called the broken function. Even when the compiled file was too short to have the relevant line number, the error underlining appeared at the end of the file. While it's still possible to debug these errors if you're familiar with this behavior and know for certain which module is causing the errors, this makes it really annoying to determine which file/function is actually broken if you're importing more than one module.

**Comment by beeb** [comment]
Duplicate https://github.com/nvarner/typst-lsp/issues/44

**Comment by beeb** [comment]
This can be closed :)

**Comment by nvarner** [comment]
Fixed in v0.3.1
