### ISSUE TITLE
[Feature Request] Symbol definitions for labels / headings

### ISSUE THREAD

**Issue by Alex-Muirhead** [nvarner/typst-lsp#59]
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

Hello, this tool is extremely useful so far! In regards to the full set of LSP interactions, it would be fantastic if document symbol were supported. This would allow for easy jumping around a given document. I would imagine the symbols would be the internal labels of the document (i.e. <intro>) or potentially the headings.

**Comment by beeb** [comment]
Good idea! I would add variables (defined with `#let`) as symbols too!

**Comment by beeb** [comment]
I'm currently working on this. Should have a PR ready soon.
