### ISSUE TITLE
Project with multiple files and single bibliography

### ISSUE THREAD

**Issue by wjslager** [nvarner/typst-lsp#64]
- **Component**: 
    - [ ] VSCode Extension
    - [x] VSCodium Extension
    - [ ] LSP (used with other editor)
- **Extension version**: v0.3.1
- **OS version and name**: Windows 10

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
When working in a project with multiple files (one for each chapter) that are included in a ``main.typ`` which has the ``bibliography()`` command, the CLI compiler can find the citation in the bibliography and produce a correct pdf, but the VSCodium extension warns ``the document does not contain a bibliography`` when editing the chapter files.

See also https://github.com/typst/typst/issues/424

**Comment by beeb** [comment]
Related https://github.com/nvarner/typst-lsp/issues/11

**Comment by FlyinPancake** [comment]
Any progress on this?

**Comment by daskol** [comment]
@nvarner Inability to complete bibliographic entries is really annoying. Is there any temporary work around or hack like hardcoded bibliography file `main.bib`?
