### ISSUE TITLE
Outline feature support

### ISSUE THREAD

**Issue by KagaJiankui** [nvarner/typst-lsp#68]
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

Implement the outline of the typst source file and display the outline in the VSCode outline view.
![image](https://user-images.githubusercontent.com/58453886/229666743-134590ee-e668-4ed7-ae9f-6fc5f717f213.png)
This feature might require building the AST of a typst source file.

**Comment by Holt59** [comment]
This would be a very useful feature, navigating medium typst file is quite painful currently.

**Comment by nvarner** [comment]
#62 should implement this. I've been out of town recently, but the PR should be reviewed tomorrow.

**Comment by gdalle** [comment]
How hard would it be to nest headings in the outline? At the moment they all appear at the same level regardless of the number of `=`. It would be a very nice QoL improvement!
