### ISSUE TITLE
[Feature Request] "Open PDF" button in VSC extension

### ISSUE THREAD

**Issue by korochun** [nvarner/typst-lsp#69]
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request
Please add the Preview button to open the produced PDF in split view, like the Markdown and LaTeX Workshop extensions do it:
<img width="24" alt="Screenshot 2023-04-04 at 5 27 55 PM" src="https://user-images.githubusercontent.com/7172267/229824643-7bc1acfc-4ba7-4110-8dd4-71cc3e2d7236.png">

**Comment by nvarner** [comment]
This should be fixed in the most recent released.
