### ISSUE TITLE
Syntax highlighting issue of italic and bold text

### ISSUE THREAD

**Issue by Alecton4** [nvarner/typst-lsp#74]
- **Component**: 
    - [x] VSCode Extension
    - [ ] VSCodium Extension
    - [ ] LSP (used with other editor)
- **Extension version**: 0.3.2
- **LSP version**: (not sure. should be the one bundled with the extension)
- **OS version and name**: OpenSUSE Tumbleweed 20230322, VSCode 1.77.0

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

First big thanks for the fabulous work!

Here's an issue with the rendering in the editor view of VSCode:

![image](https://user-images.githubusercontent.com/43232804/230557178-1718ed82-b205-449d-8fda-925ddf1598c4.png)

But the view is correct when the styled parts are put in the same line:

![image](https://user-images.githubusercontent.com/43232804/230557306-7bf6fc56-4ea3-45d7-b023-3b75c17638fa.png)

### Logs

N/A

**Comment by GeorgeHoneywood** [comment]
See here for some other syntax highlighting issues: https://github.com/nvarner/typst-lsp/issues/10

**Comment by nvarner** [comment]
With the integration of semantic highlighting into v0.6, this should be fixed. Please reopen if not.
