### ISSUE TITLE
Feature request: Config lsp server path

### ISSUE THREAD

**Issue by George-Miao** [nvarner/typst-lsp#86]
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

I'm trying to make changes and test the lsp with the vscode extension. However I find that there's no way to manually set the server path except to remove the bundled one since it looks like it takes higher precedence compare to the one I installed with cargo. 

I'd like to contribute if you're ok with that.

**Comment by nvarner** [comment]
This would be a welcome contribution.

However, for developing the LSP, it's easiest to follow the development guide in the README. That way, the LSP and extension will be built from your development environment, and a new VS Code window with the development version installed will open for testing.

**Comment by MilesCranmer** [comment]
FYI I think this is a duplicate of https://github.com/nvarner/typst-lsp/issues/55

**Comment by George-Miao** [comment]
> FYI I think this is a duplicate of https://github.com/nvarner/typst-lsp/issues/55

I see. Closing this issue then.
