### ISSUE TITLE
Supplement parameter in figure isn't working

### ISSUE THREAD

**Issue by Osares10** [nvarner/typst-lsp#88]
- **Component**: 
    - [x] VSCode Extension
    - [ ] VSCodium Extension
    - [ ] LSP (used with other editor)
- **v0.3.2**: 
- **Bundled with extension**: 
- **Fedora Linux 37 (Workstation Edition)**: 

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue

I'm trying to change the supplement parameter to use the word "figure" in my language, but the problem "unexpected argument" keeps appearing.

The following code works as intended in the web version, but not in the VS code extension:

```
@ema 

#figure(
    image("ema.jpg", width: 50%),
    caption: [Diagrama de una EMA (SMN).],
    supplement: [Figura],
)<ema>
```

**Web version**

Code:
![image](https://user-images.githubusercontent.com/16601118/232252274-0db7d382-fb73-48fb-a921-fe6c68dbdca7.png)

Result:
![Screenshot 2023-04-15 at 14-34-30 Investigación desarrollo y análisis de un sistema de observación meteorológica automático – Typst](https://user-images.githubusercontent.com/16601118/232252139-75a74f7a-7f68-442a-8be1-1cd1654cc10c.png)

**VS code extension**

Code:
![image](https://user-images.githubusercontent.com/16601118/232252263-fd04da68-786a-4014-af38-91dac9df7ff6.png)

**Comment by nvarner** [comment]
The extension was using an out-of-date version of Typst. It has just been updated, so this should be fixed now. Please reopen the issue if it does not.
