### ISSUE TITLE
Functions from modules do not syntax highlight

### ISSUE THREAD

**Issue by jesseylin** [nvarner/typst-lsp#90]
- **Component**: 
    - [x] VSCode Extension
    - [ ] VSCodium Extension
    - [ ] LSP (used with other editor)
- **Extension version**: v0.4.0
- **LSP version**: v0.4.0
- **OS version and name**: macOS 13.3

- [x] I am on the [latest](https://github.com/nvarner/typst-lsp/tags) stable version of the extension/LSP.
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.

## Issue
Looks like something is wrong with the TextMate grammar as modules are scoped as `entity.other.interpolated.typst.source.typst` instead of `entity.name.function.typst.source.typst`

Can be quickly reproduced by making a `module.typ` file with
`#let hello_world() = [hello world!]`
and then a `test.typ` file with
`#import "module.typ"
#module.hello_world()`

### Logs
![image](https://user-images.githubusercontent.com/19538877/232334677-7b1a866f-1a4c-49b7-b51a-ee682be47f53.png)

**Comment by beeb** [comment]
In case you know your way around textmate grammar definitions, I listed a few more issues here https://github.com/nvarner/typst-lsp/issues/10

**Comment by nvarner** [comment]
With the integration of semantic highlighting into v0.6, this should be fixed. Please reopen if not.
