### ISSUE TITLE
Add support for root config and `TYPST_ROOT` env

### ISSUE THREAD

**Issue by George-Miao** [nvarner/typst-lsp#98]
- [x] I have searched the [issues](https://github.com/nvarner/typst-lsp/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [discussions](https://github.com/nvarner/typst-lsp/discussions) and believe that my question is not already covered.

## Feature Request

Typst has added support for `TYPST_ROOT`, which can be used as the root dir when using absolute path import, e.g. when I set it to `$HOME/local/typst/`, all `#import "/my/absolute/path"` will be translated into `#import $HOME/local/typst/my/absolute/path`. Optionally this can also be passed in as an editor config entry.

Detail:

https://github.com/typst/typst/blob/f16ac4d258bd0981506d01456bd5f43079e00fa5/cli/src/args.rs#L14-L15

**Comment by zcorn2017** [comment]
I also encountered this bug and posted this [issue](#120), which is the last thing that blocks my migration to typst. Any chance we can fix it?

**Comment by KMIJPH** [comment]
Even when setting `rootPath`, typst-lsp ist still reporting an error for me (file not found ...).
The file compiles fine though, with the `--root` option.

v 0.13.0
